### ISSUE TITLE
Angularfire compatibility

### ISSUE THREAD

**Issue by gillarf** [mattmilan-dev/capacitor-firebase-appcheck#4]
Hi - thanks for much for this plugin.

Is it compatible with Angularfire? If so, how would we implement it? Do you have an example please?

NB I am using Angularfire 6.1.4.

Thanks

Kevin

**Comment by mattmilan-dev** [comment]
Hey Gillarf,

As long as AngularFire gives you access to the vanilla firebase namespace at any point, you should be able to use appcheck in the same way as per the example. In my companies Vue app we place the logic within the initialisation file, which i think would be the app's index.ts file (in angular) if i'm not mistaken.

Once it's initialised you should be able to use all your firebase calls in the same way as normal, regardless of whether it comes from the vanilla firebase namespace or AngularFire.

I'm not 100% however due to not using the library myself, so you may need to do some experimentation to get it fully working.

**Comment by gillarf** [comment]
Thanks @mattmilan-dev - I will try again

**Comment by jjgriff93** [comment]
@gillarf I've got this working with AngularFire v7 - not sure if it helps you with v6 but thought I'd share just in case. This is from my `app.module.ts` where I import the Angularfire modules and configure:

```typescript
import { provideAppCheck, initializeAppCheck, ReCaptchaV3Provider, CustomProvider } from '@angular/fire/app-check';
import { AppCheck } from 'capacitor-firebase-appcheck';
...
provideAppCheck(() => {
            let provider: CustomProvider | ReCaptchaV3Provider;

            // Initialise AppCheck natively if running on iOS or Android
            if (Capacitor.isNativePlatform()) {
                // Set the debug token to false if in production running on native (angular/fire wrongly sets it to true)
                if (!isDevMode()) {
                    globalThis.FIREBASE_APPCHECK_DEBUG_TOKEN = false;
                }
                AppCheck.initialize({debug: isDevMode()});
                // Use CustomProvider to get native AppCheck token
                provider = new CustomProvider({
                    getToken: async () => {
                        const { token, exp: expireTimeMillis } = await AppCheck.getAppCheckToken();
                        return { token, expireTimeMillis };
                    }
                });
            // Or use ReCAPTCHAv3 if running in web
            } else {
                provider = new ReCaptchaV3Provider(environment.firebase.recaptchaSiteKey);
            }

            // Initialise AngularFire app check using provider
            const appCheck = initializeAppCheck(getApp(), {
                provider: provider,
                isTokenAutoRefreshEnabled: true
            });
            return appCheck;
        }),
```

Essentially I use Capacitor appcheck as a custom provider but pass the result to AngularFire so it can use it to authenticate the firebase web layer

**Comment by mattmilan-dev** [comment]
Closing due to no further comments. Thanks jjgriff93 for the comment showing it working.
